-- 刪除現有表格
DROP TABLE IF EXISTS schedule_results;
DROP TABLE IF EXISTS order_materials;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS inbound_plans;
DROP TABLE IF EXISTS inventory;
DROP TABLE IF EXISTS worker_capacity;

-- 訂單主表
CREATE TABLE orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  machine_name VARCHAR(50) NOT NULL,           -- 機台名稱 (M1, M2)
  due_date DATE NOT NULL,                      -- 截止日期
  eta_date DATE,                               -- 預計完成日
  strategy VARCHAR(10) DEFAULT 'Partial',      -- 策略 (固定Partial)
  status VARCHAR(10),                          -- 狀態 (ON_TIME, LATE)
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT orders_status_chk CHECK (status IN ('ON_TIME','LATE')),
  CONSTRAINT orders_strategy_chk CHECK (strategy IN ('Partial', 'FullKit'))
);

-- 訂單材料需求 (改為實際材料名稱)
CREATE TABLE order_materials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL,
  material VARCHAR(20) NOT NULL,               -- 改為實際材料名稱
  qty_needed INT NOT NULL,                     -- 需求數量
  CONSTRAINT fk_order_materials_order
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
  CONSTRAINT om_material_chk CHECK (material IN ('氮氣管','水管','真空管'))
);

-- 庫存 (改為實際材料名稱)
CREATE TABLE inventory (
  material VARCHAR(20) PRIMARY KEY,
  qty_on_hand INT NOT NULL,
  CONSTRAINT inv_material_chk CHECK (material IN ('氮氣管','水管','真空管'))
);

-- 分批到貨計劃 (改為實際材料名稱)
CREATE TABLE inbound_plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  material VARCHAR(20) NOT NULL,
  arrival_date DATE NOT NULL,
  qty INT NOT NULL,
  CONSTRAINT inb_material_chk CHECK (material IN ('氮氣管','水管','真空管'))
);

-- 工人產能 (簡化版本，避免H2語法問題)
CREATE TABLE worker_capacity (
  work_date DATE PRIMARY KEY,
  hours_total INT NOT NULL DEFAULT 24        -- 每日總工時 (簡化為單一欄位)
);

-- 排程結果
CREATE TABLE schedule_results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL,
  eta_date DATE NOT NULL,
  status VARCHAR(10) NOT NULL,
  computed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_sched_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
  CONSTRAINT sched_status_chk CHECK (status IN ('ON_TIME','LATE'))
);

-- 新增：排程詳細執行計劃 (分批處理明細)
CREATE TABLE schedule_tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL,
  material VARCHAR(20) NOT NULL,
  work_date DATE NOT NULL,
  units_planned INT NOT NULL,                  -- 計劃處理單位數
  units_completed INT DEFAULT 0,               -- 已完成單位數
  status VARCHAR(10) DEFAULT 'PLANNED',        -- 任務狀態
  CONSTRAINT fk_schedule_tasks_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
  CONSTRAINT st_material_chk CHECK (material IN ('氮氣管','水管','真空管')),
  CONSTRAINT st_status_chk CHECK (status IN ('PLANNED','IN_PROGRESS','COMPLETED'))
);